version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  lint-ant-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: |
            python -m pip install -r requirements.txt
      - run:
          name: Lint with flake8
          command: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: Run tests
          command: |
            mkdir test-results
            python -m pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

workflows:
  build_and_test:
    jobs:
      - lint-ant-test
