version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - store_test_results:
          path: test-results

workflows:
  test_my_app:
    jobs:
      - build_and_test
