# Generated by Django 4.2.7 on 2023-11-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('number_of_games', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Game', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_GAME', 'In Game'), ('FINISHED', 'Finished')], default='WAITING', max_length=20)),
                ('board', models.TextField(blank=None, default='[[0,0,0],[0,0,0],[0,0,0]]')),
                ('actual_player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_player', to='game.user')),
                ('users', models.ManyToManyField(related_name='users', related_query_name='game', to='game.user')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='game.user')),
            ],
        ),
    ]
