# Generated by Django 4.2.7 on 2023-11-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_rename_users_game_players"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O")], default="X", max_length=1
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.user"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="users",
                related_query_name="game",
                through="game.UserGame",
                to="game.user",
            ),
        ),
    ]
