# Generated by Django 4.2.7 on 2023-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_usergame_alter_game_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.TextField(blank=None, default="[[,,],[,,],[,,]]"),
        ),
        migrations.AlterField(
            model_name="usergame",
            name="character",
            field=models.CharField(choices=[("X", "X"), ("O", "O")], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name="usergame",
            unique_together={("user", "game")},
        ),
    ]
